dependencies {
    implementation project(':playbit-common')
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

}

bootJar { enabled = false }
jar { enabled = true }
